title:              Uncle Jake's Blos
email:              ljh890322@gmail.com
description:        Let's do something for fun
author:             Jake
baseurl:            ""
url:                "https://hong9lol.github.io"

# Social Profiles
twitter_username:   none
github_username:    hong9lol
facebook_username:  none
instagram_username: jaehongn_n
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
